package main

func handle_error(err error) {
	if err != nil {
		panic(err)
	}

}
